# Generated by Django 4.2.4 on 2023-08-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_app', '0002_alter_category_intro_alter_document_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='document_videos/', verbose_name='Video'),
        ),
    ]
